import Layout from '@/components/Layout';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Home Page - Kobe Li</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col items-center'>
        <h1 className='text-9xl my-9 text-slate-400 drop-shadow-md'>Kobe Li</h1>
        <Link href="/about" className='text-xl text-gray-500 drop-shadow-sm'>{"> About"}</Link>
      </div>


    </Layout>
  )
}
